import os

filepath = r"d:\Project\CRM-Pigeon\admin-dashboard\src\pages\Customer360Page.tsx"
with open(filepath, 'r', encoding='utf-8') as f:
    content = f.read()

replacements = {
    "'Nhận biết'": "'Awareness'",
    "'Quan tâm'": "'Interest'",
    "'Cân nhắc · Lead'": "'Consideration · Lead'",
    "'Quyết định · Mua'": "'Decision · Buy'",
    "'Hỗ trợ'": "'Service'",
    "'Trung thành'": "'Loyalty'",
    "Tổng quan Customer 360": "Customer 360 Overview",
    "7 ngày qua": "Last 7 days",
    "30 ngày qua": "Last 30 days",
    "90 ngày qua": "Last 90 days",
    "CHỈ SỐ KHÁCH HÀNG": "CUSTOMER METRICS",
    "Tổng khách hàng": "Total Customers",
    "Khách hàng mới (30d)": "New Customers (30d)",
    "Khách hàng active": "Active Customers",
    "Khách quay lại": "Returning Customers",
    "so kỳ trước": "vs last period",
    "Tỷ lệ rời bỏ (Churn)": "Churn Rate",
    "Hồ sơ đầy đủ": "Complete Profiles",
    "CLV trung bình": "Average CLV",
    "Hồ sơ em bé": "Baby Profiles",
    "Hành trình & chuyển đổi khách hàng": "Customer Journey & Conversion",
    "6 giai đoạn · % chuyển đổi & đường cảm xúc theo từng bước": "6 stages · % conversion & sentiment journey",
    "Tổng tiếp cận": "Total Reach",
    "khách vào hành trình": "entered journey",
    "Chuyển đổi tổng": "Total Conversion",
    "Nhận biết → Mua hàng": "Awareness → Purchase",
    "Khách mua": "Customers Purchased",
    "hoàn tất đơn hàng": "completed orders",
    "TG chuyển đổi TB": "Avg Conversion Time",
    "ngày trung bình": "days on average",
    "Mua lại": "Repeat Purchase",
    "khách trung thành": "loyal customers",
    "CHUYỂN ĐỔI THEO GIAI ĐOẠN": "FUNNEL CONVERSION",
    "ĐƯỜNG CẢM XÚC KHÁCH HÀNG": "CUSTOMER SENTIMENT JOURNEY",
    "'Tích cực'": "'Positive'",
    "'Trung tính'": "'Neutral'",
    "'Tiêu cực'": "'Negative'",
    "Danh sách khách hàng": "Customers List",
    "Tìm theo tên, SĐT, email...": "Search by name, phone, email...",
    "Làm mới": "Refresh",
    "Thêm Khách Hàng Mới": "Add New Customer",
    "Thêm Khách Hàng": "Add Customer",
    "Khách hàng": "Customer",
    "Nguồn": "Source",
    "Hạng": "Tier",
    "Điểm": "Points",
    "Đơn hàng": "Orders",
    "Tổng chi tiêu": "Total Spend",
    "Chất lượng": "Data Quality",
    "Chỉnh sửa": "Edit",
    "Hồ sơ": "Profile",
    "SĐT": "Phone",
    "Giới tính": "Gender",
    "Ngày sinh": "Date of Birth",
    "Loại khách hàng": "Customer Type",
    "Địa chỉ": "Address",
    "Ghi chú": "Notes",
    "Điểm hiện có": "Current Points",
    "Em bé": "Babies",
    "Tên": "Name",
    "Giai đoạn": "Stage",
    "Chưa có hồ sơ em bé": "No baby profiles",
    "Chỉnh Sửa Khách Hàng": "Edit Customer",
    "Vui lòng nhập họ tên": "Please enter full name",
    "Nhập họ và tên": "Enter full name",
    "Họ và Tên": "Full Name",
    "Số Điện Thoại": "Phone Number",
    "Vui lòng nhập số điện thoại": "Please enter phone number",
    "Nhập số điện thoại": "Enter phone number",
    "Email không hợp lệ": "Invalid email",
    "Nhập email (không bắt buộc)": "Enter email (optional)",
    "Chọn giới tính": "Select gender",
    "'Nam'": "'Male'",
    "'Nữ'": "'Female'",
    "'Khác'": "'Other'",
    ">Nam<": ">Male<",
    ">Nữ<": ">Female<",
    ">Khác<": ">Other<",
    "Chọn loại khách hàng": "Select customer type",
    "Nhập địa chỉ": "Enter address",
    "Nhập ghi chú": "Enter notes",
    "'Khách hàng được tạo thành công!'": "'Customer created successfully!'",
    "'Cập nhật khách hàng thành công!'": "'Customer updated successfully!'",
    "'Lỗi khi lưu khách hàng'": "'Error saving customer'"
}

for k, v in replacements.items():
    content = content.replace(k, v)

with open(filepath, 'w', encoding='utf-8') as f:
    f.write(content)

print("Translation completed.")
